#!/bin/bash
lfil="$HOME/P/projects/logdirchanges/logfile"
tfmt='%F %T'
lfmt='%T;%e;%w%f'
watc="$HOME/P/projects/logdirchanges/dirstowatch"
inotifywait --fromfile "$watc" -o "$lfil" -r -m -q \
-e create -e modify -e delete -e move \
--timefmt "$tfmt" --format "$lfmt"|while read -r evnt;do
printf '%s\n' "$evnt">>"$lfil"
done
