#!/usr/bin/env bash

# where log file sits:
lfil="${HOME}/P/projects/logdirchanges/logfile" 
# time stamp format (strftime format):
tfmt='%F %T'
# log line format as described in 'man inotifaywatch'
lfmt='%T;%e;%w%f'
# list of filesystem paths to monitor - one per line
watc="${HOME}/P/projects/logdirchanges/dirstowatch"

# monitor. note: if recursion not requred remove -r option below!
inotifywait --fromfile "${watc}" -o "${lfil}" -m -r -q \
  # add/remove events below, comment out entire line to log everything
  -e create -e modify -e delete -e move \
  --timefmt "${tfmt}" --format "${lfmt}" |
  while read -r evnt
do
    echo "${evnt}" # log event
done
