#!/usr/bin/env bash

# where log file sits:
lfil="${HOME}/P/projects/logdirchanges/logfile" 
# time stamp format (strftime format):
tfmt='%F %T'
# log line format as described in 'man inotifaywatch'
lfmt='%T;%e;%w%f'
# list of filesystem paths to monitor - one per line
watc="${HOME}/P/projects/logdirchanges/dirstowatch"

# If you don't need recursion remove -r from line 17
# If you need to perform additional actions remove '-o "${lfil}"' from line 17
# You can add/remove events on line 18.
# Remove line 18 if you want to log evereything

inotifywait --fromfile "${watc}" -o "${lfil}" -r -m -q \
  -e create -e modify -e delete -e move \
  --timefmt "${tfmt}" --format "${lfmt}" |
  while read -r evnt 
do
  # you can add more actions here but see comment on line 13 above
  # $evnt is ; delimited 3rd filed contains file system path
  echo "${evnt}" >> ${lfil} # log event
done
